name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa

      - name: Set permissions for SSH key
        run: chmod 600 ~/.ssh/id_rsa

      - name: Copy files to EC2
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./project ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/Car_equipment

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/Car_equipment/project
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF